# Generated by Django 4.1.7 on 2023-03-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=1000)),
                ('cuisine', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=500)),
                ('directions', models.CharField(max_length=5000)),
            ],
        ),
    ]
