# Generated by Django 4.1.7 on 2023-03-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='time',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
